export interface Profile {
  userName: string,
  roleFR: string,
  roleEN: string,
  pdp: string,
  group: string,
  presentationFR: string,
  presentationEN: string,
  socialOneLink: string,
  socialOneImg: string,
  socialTwoLink: string,
  socialTwoImg: string,
  socialThreeLink: string,
  socialThreeImg: string,
}
