import { Profile } from './common/models/profile.model'

export const PROFILE: Profile[] = [

    /* --- PROJECT MANAGEMENT ---- */

    {
      userName: "Maximilien Z.",
      roleFR: "Producer",
      roleEN: "Producer",
      pdp: "../../../assets/img/pdp/max.jpg",
      group: "project-management",
      presentationFR: "Lui c'est le grand chef, enfin je pense. À vrai dire c'est un mystère. En tout cas il est sympa !",
      presentationEN: "He's the big boss, I think. To tell you the truth, it's a mystery. Anyway, he is nice!",
      /*socialOneLink: "https://www.maximilien-zimmermann.ch",
      socialOneImg: "../assets/social/website.svg",*/
      socialOneLink: "https://www.linkedin.com/in/maximilien-zimmermann-a2a290183/",
      socialOneImg: "../assets/social/linkedin.svg",
      socialTwoLink: "mailto:maximilien.zimmermann@ik.me",
      socialTwoImg: "../assets/social/mail.svg",
      socialThreeLink: "https://www.behance.net/max-zim",
      socialThreeImg: "../assets/social/behance.svg",
    },
    {
      userName: "Hugo C.",
      roleFR: "Directeur créatif",
      roleEN: "Creative Director",
      pdp: "../../../assets/img/pdp/hugo.jpg",
      group: "project-management",
      presentationFR: "Créer des jeux plus qu'un métier, une passion ! C'est cliché mais c'est si vrai.",
      presentationEN: "Creating games is more than a job, it's a passion! It's a cliché but it's so true.",
      socialOneLink: "https://www.linkedin.com/in/hugo-cluzel-983aa0177/",
      socialOneImg: "../assets/social/linkedin.svg",
      socialTwoLink: "https://petite-bryndye.itch.io/",
      socialTwoImg: "../assets/social/website.svg",
      socialThreeLink: "",
      socialThreeImg: "",
    },

    /* --- CREATIVE TEAM ---- */

    {
      userName: "Guillaume H.",
      roleFR: "Compositeur",
      roleEN: "Composer",
      pdp: "../../../assets/img/pdp/guillaume.jpg",
      group: "creative-team",
      presentationFR: "Un compositeur déterminé et passionné, en harmonie avec ses idées.",
      presentationEN: "A determined and passionate composer, in harmony with his ideas.",
      socialOneLink: "http://guillaume-hoarau.com/",
      socialOneImg: "../assets/social/website.svg",
      socialTwoLink: "https://www.linkedin.com/in/guillaume-hoarau-014324190/",
      socialTwoImg: "../assets/social/linkedin.svg",
      socialThreeLink: "https://www.youtube.com/channel/UCrbb8sZ7Xc8KRQvxHqtOx1A",
      socialThreeImg: "../assets/social/youtube.png",
    },

    /* --- GAME/LEVEL DESIGN ---- */

    /*{
      userName: "Sacha M.",
      roleFR: "Game Designer",
      roleEN: "Game Designer",
      pdp: "../../../assets/img/pdp/sacha.jpg",
      group: "game-level-design",
      presentationFR: "Il est à ce jeu ce qu'est le RGB aux gamers, à la fois inutile mais nécessaire : Game Designer",
      presentationEN: "He is to this game what RGB is to gamers, both useless and necessary: Game Designer",
      socialOneLink: "https://www.linkedin.com/in/sacha-mihman-89b70a151/",
      socialOneImg: "../assets/social/linkedin.svg",
      socialTwoLink: "",
      socialTwoImg: "",
      socialThreeLink: "",
      socialThreeImg: "",
    },*/
    {
      userName: "Timothee B.",
      roleFR: "Tech artist",
      roleEN: "Tech artist",
      pdp: "../../../assets/img/pdp/tim.jpg",
      group: "game-level-design",
      presentationFR: "Vivre un univers c'est bien, mais le créer c'est encore mieux !",
      presentationEN: "To live a universe is good, but to create it is even better!",
      socialOneLink: "https://www.linkedin.com/in/timoth%C3%A9e-bignon-b39626176/",
      socialOneImg: "../assets/social/linkedin.svg",
      socialTwoLink: "",
      socialTwoImg: "",
      socialThreeLink: "",
      socialThreeImg: "",
    },
    {
      userName: "Augustin P.",
      roleFR: "Level Designer",
      roleEN: "Level Designer",
      pdp: "../../../assets/img/pdp/augustin.jpg",
      group: "game-level-design",
      presentationFR: "Il tente encore aujourd'hui d'inventer le niveau parfait..      ",
      presentationEN: "He is still trying to invent the perfect level...",
      socialOneLink: "https://www.instagram.com/augustin_porcher/",
      socialOneImg: "../assets/social/instagram.png",
      socialTwoLink: "",
      socialTwoImg: "",
      socialThreeLink: "",
      socialThreeImg: "",
    },
    {
      userName: "Alexandre A.",
      roleFR: "Game Designer",
      roleEN: "Game Designer",
      pdp: "../../../assets/img/pdp/alexandre.jpg",
      group: "game-level-design",
      presentationFR: "Futur Hokage du game design ! « kept you waiting huh ? »",
      presentationEN: "Future Hokage of game design! « kept you waiting huh? »",
      socialOneLink: "https://alexandreafonso.fr/",
      socialOneImg: "../assets/social/website.svg",
      socialTwoLink: "https://www.linkedin.com/in/alexandre-afonso-18a854119/",
      socialTwoImg: "../assets/social/linkedin.svg",
      socialThreeLink: "Afonso.rodrigues.alexandre@gmail.com",
      socialThreeImg: "../assets/social/mail.svg",
    },


    /* --- DEVELOPPEMENT ---- */

    {
      userName: "Clément D.",
      roleFR: "Développeur",
      roleEN: "Developer",
      pdp: "../../../assets/img/pdp/clement.jpg",
      group: "developpement",
      presentationFR: "Un amateur de jeux-vidéo en quête de projets sur lesquels travailler.",
      presentationEN: "A video game enthusiast looking for projects to work on.",
      socialOneLink: "",
      socialOneImg: "",
      socialTwoLink: "",
      socialTwoImg: "",
      socialThreeLink: "",
      socialThreeImg: "",
    },
    {
      userName: "Thomas G.",
      roleFR: "Animateur 3D",
      roleEN: "3D Animator",
      pdp: "../../../assets/img/pdp/tomas.jpg",
      group: "developpement",
      presentationFR: "Après toutes ces années, il essaie tant bien que mal d'apprendre a dessiner. Résultat : pas top",
      presentationEN: "After all these years, he tries to learn how to draw. Result : not great",
      socialOneLink: "https://www.instagram.com/___thomas_gross__/",
      socialOneImg: "../assets/social/instagram.png",
      socialTwoLink: "",
      socialTwoImg: "",
      socialThreeLink: "",
      socialThreeImg: "",
    },

    /* --- MODELERS ---- */

    {
      userName: "Adjé B.",
      roleFR: "Modélisateur 3D",
      roleEN: "3D modeler",
      pdp: "../../../assets/img/pdp/adje.jpg",
      group: "modelers",
      presentationFR: "Un modélisateur 3D fort sympathique, toujours là pour relever les défis et motiver les troupes.",
      presentationEN: "A very nice 3D modeler, always there to meet the challenges and motivate the troops.",
      socialOneLink: "https://www.linkedin.com/in/adjé-bansou-4187951a0",
      socialOneImg: "../assets/social/linkedin.svg",
      socialTwoLink: "https://www.artstation.com/bs_adje",
      socialTwoImg: "../assets/social/artstation.svg",
      socialThreeLink: "",
      socialThreeImg: "",
    },
    {
      userName: "Maël G.",
      roleFR: "Modélisateur 3D",
      roleEN: "3D modeler",
      pdp: "../../../assets/img/pdp/mael.jpg",
      group: "modelers",
      presentationFR: "Lui c'est le modélisateur de l'environnement du jeu. Il créé des murs plus futuristes que jamais.",
      presentationEN: "He is the modeler of the game environment. He creates walls more futuristic than ever.",
      socialOneLink: "https://www.linkedin.com/in/maël-gaubicher-6265a4194/",
      socialOneImg: "../assets/social/linkedin.svg",
      socialTwoLink: "https://www.instagram.com/maelgaubicher/",
      socialTwoImg: "../assets/social/instagram.png",
      socialThreeLink: "",
      socialThreeImg: "",
    },
    {
      userName: "Gaspard D.",
      roleFR: "Modélisateur 3D",
      roleEN: "3D modeler",
      pdp: "../../../assets/img/pdp/gaspard.jpg",
      group: "modelers",
      presentationFR: "Il est toujours prêt à partir combattre les pires problèmes de topologie sur ses models 3D.",
      presentationEN: "He is always ready to go to fight the worst topology problems on his 3D models.",
      socialOneLink: "https://www.artstation.com/drap",
      socialOneImg: "../assets/social/artstation.svg",
      socialTwoLink: "https://sketchfab.com/drap",
      socialTwoImg: "../assets/social/sketchfab.svg",
      socialThreeLink: "",
      socialThreeImg: "",
    }

    /* --- DRAWERS ---- */
    /* A ajouter */
  ];
