import { Profile } from './common/models/profile.model'

export const PROFILE: Profile[] = [

    /* --- PROJECT MANAGEMENT ---- */

    {
      userName: "Maximilien Z.",
      roleFR: "Chef de projet",
      roleEN: "Project Manager",
      pdp: "../../../assets/img/pdp/max.jpg",
      group: "project-management",
      presentationFR: "Oui c'est lui le grand chef, enfin je pense. À vrai dire c'est un mystère. En tout cas il est sympa !",
      presentationEN: "Yes, he's the big boss, I think. To tell the truth, it's a mystery. In any case he is nice!",
      /*socialOneLink: "https://www.maximilien-zimmermann.ch",
      socialOneImg: "../assets/social/website.svg",*/
      socialOneLink: "https://www.linkedin.com/in/maximilien-zimmermann-a2a290183/",
      socialOneImg: "../assets/social/linkedin.svg",
      socialTwoLink: "mailto:maximilien.zimmermann@ik.me",
      socialTwoImg: "../assets/social/mail.svg",
      socialThreeLink: "https://www.behance.net/maximilzimmerm1",
      socialThreeImg: "../assets/social/behance.svg",
    },
    {
      userName: "Quentin F.",
      roleFR: "Chef de projet",
      roleEN: "Project Manager",
      pdp: "../../../assets/img/pdp/quentin.jpeg",
      group: "project-management",
      presentationFR: "AKA Carcaroux, actuellement à la recherche d'un concurrent à sa taille sur Mario Kart.",
      presentationEN: "AKA Carcaroux, currently looking for a worthy competitor on Mario Kart.",
      socialOneLink: "https://www.linkedin.com/in/quentin-fert-6876b2164/",
      socialOneImg: "../assets/social/linkedin.svg",
      socialTwoLink: "https://www.arcadia-corporation.com/community/carcaroux",
      socialTwoImg: "../assets/social/website.svg",
      socialThreeLink: "mailto:quentin.fert.pro@gmail.com",
      socialThreeImg: "../assets/social/mail.svg",
    },
    {
      userName: "Antoine R.",
      roleFR: "Contributeur",
      roleEN: "Contributor",
      pdp: "../../../assets/img/pdp/antoine.jpg",
      group: "project-management",
      presentationFR: "Grâce à lui vous allez pouvoir terminer un projet de qualité tout en prenant vos pauses cafés.",
      presentationEN: "Thanks to him you will be able to finish a quality project while taking your coffee breaks.",
      socialOneLink: "https://www.linkedin.com/in/antoine-rigitano-038862b3/",
      socialOneImg: "../assets/social/linkedin.svg",
      socialTwoLink: "https://www.behance.net/arigitano",
      socialTwoImg: "../assets/social/behance.svg",
      socialThreeLink: "",
      socialThreeImg: "",
    },

    /* --- CREATIVE TEAM ---- */

    {
      userName: "Julie Z.",
      roleFR: "Scénariste",
      roleEN: "Scriptwriter",
      pdp: "../../../assets/img/pdp/julie.png",
      group: "creative-team",
      presentationFR: "Quand elle n'est pas occupée à faire de l'humour, ça lui arrive d'écrire des scénarios.",
      presentationEN: "When she's not busy making humor, she sometimes writes screenplays.",
      socialOneLink: "https://www.facebook.com/ju.zahar/",
      socialOneImg: "../assets/social/facebook.svg",
      socialTwoLink: "https://www.youtube.com/channel/UCMSoFWxKgEU753xEcv5VjlA",
      socialTwoImg: "../assets/social/youtube.svg",
      socialThreeLink: "",
      socialThreeImg: "",
    },
    {
      userName: "Guillaume H.",
      roleFR: "Compositeur",
      roleEN: "Composer",
      pdp: "../../../assets/img/pdp/guillaume.png",
      group: "creative-team",
      presentationFR: "Un compositeur déterminé, en harmonie avec ses idées. Il les accorde dans le but de créer l'accord parfait.",
      presentationEN: "A determined composer, in harmony with his ideas. He tunes them in order to create the perfect chord.",
      socialOneLink: "http://guillaume-hoarau.com/",
      socialOneImg: "../assets/social/website.svg",
      socialTwoLink: "https://www.linkedin.com/in/guillaume-hoarau-014324190/",
      socialTwoImg: "../assets/social/linkedin.svg",
      socialThreeLink: "https://www.youtube.com/channel/UCrbb8sZ7Xc8KRQvxHqtOx1A",
      socialThreeImg: "../assets/social/youtube.svg",
    },

    /* --- GAME/LEVEL DESIGN ---- */

    {
      userName: "Sacha M.",
      roleFR: "Game Designer",
      roleEN: "Game Designer",
      pdp: "../../../assets/img/pdp/sacha.png",
      group: "game-level-design",
      presentationFR: "Je suis à ce jeu ce qu'est le RGB aux g@mers, à la fois inutile mais nécessaire : Game Designer",
      presentationEN: "I am to this game what RGB is to g@mers, at the same time useless but necessary: ​​Game Designer.",
      socialOneLink: "https://www.linkedin.com/in/sacha-mihman-89b70a151/",
      socialOneImg: "../assets/social/linkedin.svg",
      socialTwoLink: "",
      socialTwoImg: "",
      socialThreeLink: "",
      socialThreeImg: "",
    },

    /* --- DEVELOPPEMENT ---- */

    {
      userName: "Maxime B.",
      roleFR: "Développeur",
      roleEN: "Developer",
      pdp: "../../../assets/img/pdp/maxime.jpg",
      group: "developpement",
      presentationFR: "Un developpeur qui cherche a faire de sa passion son métier.",
      presentationEN: "A developer who wants to make his passion his job.",
      socialOneLink: "https://github.com/maxo98",
      socialOneImg: "../assets/social/github.svg",
      socialTwoLink: "",
      socialTwoImg: "",
      socialThreeLink: "",
      socialThreeImg: "",
    },

    {
      userName: "Nemerod D.",
      roleFR: "Développeur",
      roleEN: "Developer",
      pdp: "../../../assets/img/pdp/nemerod.png",
      group: "developpement",
      presentationFR: "Il n'est que un pixel dans un ocean qui est l’écran du monde.",
      presentationEN: "He is only a pixel in an ocean which is the screen of the world.",
      socialOneLink: "https://github.com/nemerod",
      socialOneImg: "../assets/social/github.svg",
      socialTwoLink: "https://twitter.com/nemerodDSCP",
      socialTwoImg: "../assets/social/twitter.svg",
      socialThreeLink: "https://steamcommunity.com/id/ORIATEC/",
      socialThreeImg: "../assets/social/steam.svg",
    },

    /* --- MODELERS ---- */

    {
      userName: "Adjé B.",
      roleFR: "Modélisateur 3D",
      roleEN: "3D modeler",
      pdp: "../../../assets/img/pdp/adje.jpg",
      group: "modelers",
      presentationFR: "Un modélisateur 3D fort sympathique, toujours là pour relever les défis et motiver les troupes.",
      presentationEN: "A very nice 3D modeler, always there to meet the challenges and motivate the troops.",
      socialOneLink: "https://www.linkedin.com/in/adjé-bansou-4187951a0",
      socialOneImg: "../assets/social/linkedin.svg",
      socialTwoLink: "https://www.artstation.com/bs_adje",
      socialTwoImg: "../assets/social/artstation.svg",
      socialThreeLink: "",
      socialThreeImg: "",
    },
    {
      userName: "Gaspard D.",
      roleFR: "Modélisateur 3D",
      roleEN: "3D modeler",
      pdp: "../../../assets/img/pdp/gaspard.png",
      group: "modelers",
      presentationFR: "Il est toujours prêt à partir combattre les pires problèmes de topologie sur ses models 3D.",
      presentationEN: "He is always ready to go to fight the worst topology problems on his 3D models.",
      socialOneLink: "https://www.artstation.com/drap",
      socialOneImg: "../assets/social/artstation.svg",
      socialTwoLink: "https://sketchfab.com/drap",
      socialTwoImg: "../assets/social/sketchfab.svg",
      socialThreeLink: "",
      socialThreeImg: "",
    },
    {
      userName: "Thomas G.",
      roleFR: "Animateur 3D/Rigger",
      roleEN: "3D Animator/rigger",
      pdp: "../../../assets/img/pdp/tomas.png",
      group: "modelers",
      presentationFR: "Essaie toujours d'apprendre a dessiner.",
      presentationEN: "Always try to learn to draw.",
      socialOneLink: "https://www.instagram.com/___thomas_gross__/",
      socialOneImg: "../assets/social/instagram.svg",
      socialTwoLink: "",
      socialTwoImg: "",
      socialThreeLink: "",
      socialThreeImg: "",
    },

    /* --- DRAWERS ---- */

    {
      userName: "Onyx",
      roleFR: "Dessinateur",
      roleEN: "Drawer",
      pdp: "../../../assets/img/pdp/onyx.png",
      group: "drawers",
      presentationFR: "Onyx, dessinateur pas productif mais avec quelques bonnes idées (il espère)",
      presentationEN: "Onyx, drawer not productive but with some good ideas (he hopes)",
      socialOneLink: "",
      socialOneImg: "",
      socialTwoLink: "",
      socialTwoImg: "",
      socialThreeLink: "",
      socialThreeImg: "",
    },

  ];
