import { Profile } from './common/models/profile.model'

export const PROFILE: Profile[] = [

    /* --- PROJECT MANAGEMENT ---- */

    {
      userName: "Maximilien Z.",
      roleFR: "Chef de projet",
      roleEN: "Project Manager",
      pdp: "../../../assets/img/pdp/max.jpg",
      group: "project-management",
      presentationFR: "Lui c'est le grand chef, enfin je pense. À vrai dire c'est un mystère. En tout cas il est sympa !",
      presentationEN: "He's the big boss, I think. To tell you the truth, it's a mystery. Anyway, he is nice!",
      /*socialOneLink: "https://www.maximilien-zimmermann.ch",
      socialOneImg: "../assets/social/website.svg",*/
      socialOneLink: "https://www.linkedin.com/in/maximilien-zimmermann-a2a290183/",
      socialOneImg: "../assets/social/linkedin.svg",
      socialTwoLink: "mailto:maximilien.zimmermann@ik.me",
      socialTwoImg: "../assets/social/mail.svg",
      socialThreeLink: "https://www.behance.net/max-zim",
      socialThreeImg: "../assets/social/behance.svg",
    },
    {
      userName: "Quentin F.",
      roleFR: "Chef de projet",
      roleEN: "Project Manager",
      pdp: "../../../assets/img/pdp/quentin.jpeg",
      group: "project-management",
      presentationFR: "AKA Carcaroux, actuellement à la recherche d'un concurrent à sa taille sur Mario Kart.",
      presentationEN: "AKA Carcaroux, currently looking for a worthy competitor on Mario Kart.",
      socialOneLink: "https://www.linkedin.com/in/quentin-fert-6876b2164/",
      socialOneImg: "../assets/social/linkedin.svg",
      socialTwoLink: "https://www.arcadia-corporation.com/community/carcaroux",
      socialTwoImg: "../assets/social/website.svg",
      socialThreeLink: "mailto:quentin.fert.pro@gmail.com",
      socialThreeImg: "../assets/social/mail.svg",
    },
    {
      userName: "Antoine R.",
      roleFR: "Contributeur",
      roleEN: "Contributor",
      pdp: "../../../assets/img/pdp/antoine.jpg",
      group: "project-management",
      presentationFR: "Grâce à lui vous allez pouvoir terminer un projet de qualité tout en prenant vos pauses cafés.",
      presentationEN: "Thanks to him you will be able to finish a quality project while taking your coffee breaks.",
      socialOneLink: "https://www.linkedin.com/in/antoine-rigitano-038862b3/",
      socialOneImg: "../assets/social/linkedin.svg",
      socialTwoLink: "https://www.behance.net/arigitano",
      socialTwoImg: "../assets/social/behance.svg",
      socialThreeLink: "",
      socialThreeImg: "",
    },

    /* --- CREATIVE TEAM ---- */

    {
      userName: "Julie Z.",
      roleFR: "Scénariste",
      roleEN: "Scriptwriter",
      pdp: "../../../assets/img/pdp/julie.jpg",
      group: "creative-team",
      presentationFR: "Quand elle n'est pas occupée à faire de l'humour, ça lui arrive d'écrire des scénarios.",
      presentationEN: "When she's not busy making humor, she sometimes writes screenplays.",
      socialOneLink: "https://www.facebook.com/ju.zahar/",
      socialOneImg: "../assets/social/facebook.svg",
      socialTwoLink: "https://www.youtube.com/channel/UCMSoFWxKgEU753xEcv5VjlA",
      socialTwoImg: "../assets/social/youtube.svg",
      socialThreeLink: "",
      socialThreeImg: "",
    },
    {
      userName: "Guillaume H.",
      roleFR: "Compositeur",
      roleEN: "Composer",
      pdp: "../../../assets/img/pdp/guillaume.jpg",
      group: "creative-team",
      presentationFR: "Un compositeur déterminé, en harmonie avec ses idées. Il les accorde afin de créer l'accord parfait.",
      presentationEN: "A determined composer, in harmony with his ideas. He tunes them to create the perfect chord.",
      socialOneLink: "http://guillaume-hoarau.com/",
      socialOneImg: "../assets/social/website.svg",
      socialTwoLink: "https://www.linkedin.com/in/guillaume-hoarau-014324190/",
      socialTwoImg: "../assets/social/linkedin.svg",
      socialThreeLink: "https://www.youtube.com/channel/UCrbb8sZ7Xc8KRQvxHqtOx1A",
      socialThreeImg: "../assets/social/youtube.svg",
    },
    {
      userName: "Sadjidat A.",
      roleFR: "Community manager",
      roleEN: "Community manager",
      pdp: "../../../assets/img/pdp/sadidjat.jpeg",
      group: "creative-team",
      presentationFR: "Les réseaux sociaux semblent n’avoir aucun secret pour elle, attention aux stalks elle vous surveille !",
      presentationEN: "Social networks seem to have no secret for her, beware of stalks she is watching you!",
      socialOneLink: "https://www.instagram.com/san_eden2/",
      socialOneImg: "../assets/social/instagram.png",
      socialTwoLink: "",
      socialTwoImg: "",
      socialThreeLink: "",
      socialThreeImg: "",
    },

    /* --- GAME/LEVEL DESIGN ---- */

    {
      userName: "Sacha M.",
      roleFR: "Game Designer",
      roleEN: "Game Designer",
      pdp: "../../../assets/img/pdp/sacha.jpg",
      group: "game-level-design",
      presentationFR: "Il est à ce jeu ce qu'est le RGB aux gamers, à la fois inutile mais nécessaire : Game Designer",
      presentationEN: "He is to this game what RGB is to gamers, both useless and necessary: Game Designer",
      socialOneLink: "https://www.linkedin.com/in/sacha-mihman-89b70a151/",
      socialOneImg: "../assets/social/linkedin.svg",
      socialTwoLink: "",
      socialTwoImg: "",
      socialThreeLink: "",
      socialThreeImg: "",
    },
    {
      userName: "Augustin P.",
      roleFR: "Level Designer",
      roleEN: "Level Designer",
      pdp: "../../../assets/img/pdp/augustin.jpg",
      group: "game-level-design",
      presentationFR: "Il tente encore aujourd'hui d'inventer le niveau parfait mais sa quête n'a jamais abouti...      ",
      presentationEN: "He is still trying to invent the perfect level but his quest never came to a conclusion...",
      socialOneLink: "https://www.instagram.com/augustin_porcher/",
      socialOneImg: "../assets/social/instagram.png",
      socialTwoLink: "",
      socialTwoImg: "",
      socialThreeLink: "",
      socialThreeImg: "",
    },

    /* --- DEVELOPPEMENT ---- */

    {
      userName: "Maxime B.",
      roleFR: "Développeur",
      roleEN: "Developer",
      pdp: "../../../assets/img/pdp/maxime.jpg",
      group: "developpement",
      presentationFR: "Un développeur passionné qui cherche a faire de sa passion son métier.",
      presentationEN: "A passionate developer who wants to make his passion his job.",
      socialOneLink: "https://github.com/maxo98",
      socialOneImg: "../assets/social/github.svg",
      socialTwoLink: "",
      socialTwoImg: "",
      socialThreeLink: "",
      socialThreeImg: "",
    },
    {
      userName: "Clément D.",
      roleFR: "Développeur",
      roleEN: "Developer",
      pdp: "../../../assets/img/pdp/clement.jpg",
      group: "developpement",
      presentationFR: "Un amateur de jeux-vidéo en quête de projets sur lesquels travailler.",
      presentationEN: "A video game enthusiast looking for projects to work on.",
      socialOneLink: "",
      socialOneImg: "",
      socialTwoLink: "",
      socialTwoImg: "",
      socialThreeLink: "",
      socialThreeImg: "",
    },
    {
      userName: "Nemerod D.",
      roleFR: "Développeur",
      roleEN: "Developer",
      pdp: "../../../assets/img/pdp/nemerod.jpg",
      group: "developpement",
      presentationFR: "Il n'est que un pixel dans un ocean qui est l’écran du monde.",
      presentationEN: "He is only a pixel in an ocean which is the screen of the world.",
      socialOneLink: "https://github.com/nemerod",
      socialOneImg: "../assets/social/github.svg",
      socialTwoLink: "https://twitter.com/nemerodDSCP",
      socialTwoImg: "../assets/social/twitter.png",
      socialThreeLink: "https://steamcommunity.com/id/ORIATEC/",
      socialThreeImg: "../assets/social/steam.svg",
    },

    /* --- MODELERS ---- */

    {
      userName: "Adjé B.",
      roleFR: "Modélisateur 3D",
      roleEN: "3D modeler",
      pdp: "../../../assets/img/pdp/adje.jpg",
      group: "modelers",
      presentationFR: "Un modélisateur 3D fort sympathique, toujours là pour relever les défis et motiver les troupes.",
      presentationEN: "A very nice 3D modeler, always there to meet the challenges and motivate the troops.",
      socialOneLink: "https://www.linkedin.com/in/adjé-bansou-4187951a0",
      socialOneImg: "../assets/social/linkedin.svg",
      socialTwoLink: "https://www.artstation.com/bs_adje",
      socialTwoImg: "../assets/social/artstation.svg",
      socialThreeLink: "",
      socialThreeImg: "",
    },
    {
      userName: "Gaspard D.",
      roleFR: "Modélisateur 3D",
      roleEN: "3D modeler",
      pdp: "../../../assets/img/pdp/gaspard.jpg",
      group: "modelers",
      presentationFR: "Il est toujours prêt à partir combattre les pires problèmes de topologie sur ses models 3D.",
      presentationEN: "He is always ready to go to fight the worst topology problems on his 3D models.",
      socialOneLink: "https://www.artstation.com/drap",
      socialOneImg: "../assets/social/artstation.svg",
      socialTwoLink: "https://sketchfab.com/drap",
      socialTwoImg: "../assets/social/sketchfab.svg",
      socialThreeLink: "",
      socialThreeImg: "",
    },
    {
      userName: "Thomas G.",
      roleFR: "Animateur 3D",
      roleEN: "3D Animator",
      pdp: "../../../assets/img/pdp/tomas.jpg",
      group: "modelers",
      presentationFR: "Après toutes ces années, il essaie tant bien que mal d'apprendre a dessiner. Résultat : pas top",
      presentationEN: "After all these years, he tries to learn how to draw. Result : not great",
      socialOneLink: "https://www.instagram.com/___thomas_gross__/",
      socialOneImg: "../assets/social/instagram.png",
      socialTwoLink: "",
      socialTwoImg: "",
      socialThreeLink: "",
      socialThreeImg: "",
    },

    /* --- DRAWERS ---- */

    {
      userName: "Pat'",
      roleFR: "Dessinateur",
      roleEN: "Drawer",
      pdp: "../../../assets/img/pdp/pat.jpg",
      group: "drawers",
      presentationFR: "Il lui manque des bouts de peau, il grogne souvent et on sait pas pourquoi il tente toujours de mordre.",
      presentationEN: "He is missing pieces of skin, he often growls and we do not know why he always tries to bite.",
      socialOneLink: "https://www.facebook.com/LostShop313",
      socialOneImg: "../assets/social/facebook.svg",
      socialTwoLink: "https://www.instagram.com/lostshop313",
      socialTwoImg: "../assets/social/instagram.png",
      socialThreeLink: "https://www.etsy.com/fr/shop/LostShop313",
      socialThreeImg: "../assets/social/website.svg",
    },
    {
      userName: "I5olde'",
      roleFR: "Dessinatrice",
      roleEN: "Drawer",
      pdp: "../../../assets/img/pdp/i5olde.jpg",
      group: "drawers",
      presentationFR: "Elle c'est un petit coup de pouce en dessin pour l'équipe, et de temps en temps un léger coup de pied !",
      presentationEN: "She is a little help in drawing for the team, and from time to time a little kick!",
      socialOneLink: "",
      socialOneImg: "",
      socialTwoLink: "",
      socialTwoImg: "",
      socialThreeLink: "",
      socialThreeImg: "",
    },
    {
      userName: "Onyx",
      roleFR: "Dessinateur",
      roleEN: "Drawer",
      pdp: "../../../assets/img/pdp/onyx.jpg",
      group: "drawers",
      presentationFR: "Onyx, un dessinateur avec des bonnes idées qui a pas peur d'apprendre en s'aventurant dans du nouveau.",
      presentationEN: "Onyx, a drawer with good ideas who is not afraid to learn by venturing into new things.",
      socialOneLink: "",
      socialOneImg: "",
      socialTwoLink: "",
      socialTwoImg: "",
      socialThreeLink: "",
      socialThreeImg: "",
    },

  ];
